
import { useGSAP } from '@gsap/react';
import gsap from 'gsap';

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Lassi Kaukonen (https://sketchfab.com/thesidekick)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/basketball-8d17cb0964334a6cbe4b0e293c238956
Title: Basketball
*/

import  { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';

const Basketball = (props) => {
    const { nodes, materials } = useGLTF('/models/basketball.glb');
    const basketballRef = useRef();

    // Bounce state variables
    const speed = 3; // Speed of the bounce
    const amplitude = 0.5; // Height of the bounce

    // Animation loop for bouncing effect
    useFrame((state) => {
        if (basketballRef.current) {
            const time = state.clock.getElapsedTime();
            basketballRef.current.position.y = Math.abs(Math.sin(time * speed)) * amplitude -10; // Bounce effect
        }
    });

    return (
        <group {...props} dispose={null} ref={basketballRef} scale={0.45} >
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_2.geometry}
                material={materials.Basketball_size6}
                rotation={[-Math.PI / 2, 0, 0]}
            />
        </group>
    );
};

useGLTF.preload('/models/basketball.glb');

export default Basketball;

//
// rembrandt
//
// city
// Made by @NikkitaFTW & contributors inspired by the gltfjsx cli

